import { useCallback, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import * as Print from 'expo-print';
import QRCode from 'qrcode';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { ArrowRightLeft, ClipboardCheck, Clock3, MapPin, PackagePlus, Printer, ScanLine, Trash2 } from 'lucide-react-native';

import { ActionCard, PageHeader, StatusChip, Surface } from '@/components/inventory-ui';
import { EmptyState, LoadingScreen, Screen } from '@/components/ui';
import { BRAND, TYPE } from '@/constants/brand';
import { fetchStorageContainer } from '@/lib/api';
import { useAuth } from '@/providers/auth-provider';
import type { StorageContainer } from '@/types/domain';

export default function ContainerScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { session } = useAuth(); const [data, setData] = useState<StorageContainer | null>(null); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!session || !id) return; setError(''); try { setData(await fetchStorageContainer(session.token, id)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Container unavailable'); } }, [id, session]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (!data && !error) return <LoadingScreen label="Opening container" />;
  if (!data) return <Screen><PageHeader title="Container" /><EmptyState error title="Container unavailable" message={error} /></Screen>;
  const location = data.rack && data.shelf ? `${data.rack.name} → ${data.shelf.name}` : 'Location not assigned';
  async function printLabel() { try { const svg = await QRCode.toString(data!.containerId, { type: 'svg', margin: 0, width: 260, errorCorrectionLevel: 'M' }); const escape = (value: string) => value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char] || char); await Print.printAsync({ html: `<!doctype html><html><head><meta name="viewport" content="width=device-width"><style>@page{margin:12mm}body{font-family:Arial,sans-serif;text-align:center;color:#14213d}.label{border:3px solid #14213d;border-radius:18px;padding:28px;display:inline-block}.brand{color:#c2185b;font-weight:800;letter-spacing:2px}.qr{width:260px;margin:18px auto}.id{font:800 28px monospace;letter-spacing:1px}.name{font-size:22px;font-weight:700;margin-top:9px}</style></head><body><div class="label"><div class="brand">STRATOS ENTERPRISE</div><div class="name">${escape(data!.name)}</div><div class="qr">${svg}</div><div class="id">${escape(data!.containerId)}</div><p>Scan to load current contents from the inventory database.</p></div></body></html>` }); } catch (error) { Alert.alert('Unable to print label', error instanceof Error ? error.message : 'Try again.'); } }
  return <Screen><PageHeader title="Container contents" scan /><Surface style={styles.hero}><View style={styles.top}><View style={styles.main}><Text style={styles.eyebrow}>CONTAINER</Text><Text style={styles.title}>{data.name}</Text><Text style={styles.id}>{data.containerId}</Text></View><StatusChip label={data.status} accent="green" /></View><View style={styles.location}><MapPin size={17} color={BRAND.violet} /><Text style={styles.locationText}>{location}</Text></View><Text style={styles.kind}>{data.type === 'MOVABLE_PROJECT' ? 'Movable project container' : 'Fixed bin'}{data.project ? ` · ${data.project.name}` : ''}</Text><View style={styles.stats}><Stat label="Item Types" value={data.itemTypes} /><Stat label="Total Units" value={data.totalUnits} /></View></Surface>
    <Text style={styles.heading}>Current contents</Text>{data.items.length ? data.items.map((row) => <Surface key={row.id} style={styles.item}><View style={styles.main}><Text style={styles.name}>{row.item.name}</Text><Text style={styles.meta}>{row.item.barcode || row.item.sku}{row.batch ? ` · Batch ${row.batch.batchNo}` : ''}</Text><Text style={styles.meta}>{row.condition.replaceAll('_', ' ')}{row.warrantyEndsAt ? ` · Warranty ${new Date(row.warrantyEndsAt).toLocaleDateString()}` : ''}</Text></View><Text style={styles.qty}>{row.qty} {row.item.unit}</Text></Surface>) : <EmptyState title="Container is empty" message="Use Scan Item Into Container to add its first item." />}
    <Text style={styles.heading}>What do you want to do?</Text><View style={styles.actions}><ActionCard label="Scan Item Into Container" accent="red" icon={<PackagePlus size={27} color={BRAND.red} />} onPress={() => router.push({ pathname: '/container/add/[id]', params: { id: String(data.id) } } as never)} /><ActionCard label="Remove Item" accent="amber" icon={<Trash2 size={26} color={BRAND.amber} />} onPress={() => router.push({ pathname: '/container/remove/[id]', params: { id: String(data.id) } } as never)} /><ActionCard label="Move Container" accent="violet" icon={<ArrowRightLeft size={26} color={BRAND.violet} />} onPress={() => router.push({ pathname: '/container/move/[id]', params: { id: String(data.id) } } as never)} /><ActionCard label="Count Contents" accent="green" icon={<ClipboardCheck size={26} color={BRAND.green} />} onPress={() => router.push({ pathname: '/container/count/[id]', params: { id: String(data.id) } } as never)} /><ActionCard label="View History" accent="blue" icon={<Clock3 size={26} color={BRAND.blue} />} onPress={() => router.push('/history' as never)} /><ActionCard label="Print Container Label" accent="neutral" icon={<Printer size={26} color={BRAND.inkSoft} />} onPress={() => void printLabel()} /></View>
    <Surface style={styles.rule}><ScanLine size={19} color={BRAND.green} /><Text style={styles.ruleText}>Scanning this container only opens its current contents. It never posts Stock In or Stock Out.</Text></Surface>
  </Screen>;
}

function Stat({ label, value }: { label: string; value: number }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ hero: { padding: 17 }, top: { flexDirection: 'row', gap: 10 }, main: { flex: 1, minWidth: 0 }, eyebrow: { color: BRAND.red, fontFamily: TYPE.body, fontSize: 10, fontWeight: '800', letterSpacing: 1.2 }, title: { marginTop: 4, color: BRAND.ink, fontFamily: TYPE.body, fontSize: 21, fontWeight: '800' }, id: { marginTop: 4, color: BRAND.muted, fontFamily: TYPE.body, fontSize: 13 }, location: { marginTop: 16, flexDirection: 'row', alignItems: 'center', gap: 7 }, locationText: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 13, fontWeight: '700' }, kind: { marginTop: 6, color: BRAND.violet, fontFamily: TYPE.body, fontSize: 12, fontWeight: '700' }, stats: { marginTop: 15, flexDirection: 'row', gap: 9 }, stat: { flex: 1, borderRadius: 12, backgroundColor: BRAND.canvas, padding: 12 }, statValue: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 22, fontWeight: '800' }, statLabel: { color: BRAND.muted, fontFamily: TYPE.body, fontSize: 10 }, heading: { marginTop: 22, marginBottom: 10, color: BRAND.ink, fontFamily: TYPE.body, fontSize: 19, fontWeight: '800' }, item: { minHeight: 74, marginBottom: 8, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10 }, name: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 14, fontWeight: '700' }, meta: { marginTop: 3, color: BRAND.muted, fontFamily: TYPE.body, fontSize: 10 }, qty: { color: BRAND.red, fontFamily: TYPE.body, fontSize: 15, fontWeight: '800' }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, rule: { marginTop: 18, padding: 14, flexDirection: 'row', gap: 9, backgroundColor: BRAND.greenSoft }, ruleText: { flex: 1, color: BRAND.green, fontFamily: TYPE.body, fontSize: 11, lineHeight: 16, fontWeight: '700' } });
