import { useCallback, useMemo, useRef, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as Crypto from 'expo-crypto';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { CheckCircle2, Minus, Plus, ScanLine, X } from 'lucide-react-native';

import { OutlineButton, PageHeader, RedButton, StatusChip, Surface } from '@/components/inventory-ui';
import { AdditionalFormFields, mergeAdditionalFieldsIntoNotes, type AdditionalFormField } from '@/components/additional-form-fields';
import { LoadingScreen, Screen } from '@/components/ui';
import { BRAND, TYPE } from '@/constants/brand';
import { addContainerItems, ApiError, fetchStorageContainer } from '@/lib/api';
import { getInstallationId } from '@/lib/storage';
import { isDuplicateScan } from '@/lib/inventory-rules';
import { useAuth } from '@/providers/auth-provider';
import { useSyncedData } from '@/providers/data-provider';
import { useOfflineInventory } from '@/providers/offline-inventory-provider';
import type { InventoryCartLine, InventoryItem, StorageContainer } from '@/types/domain';

export default function AddContainerItemsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { session } = useAuth(); const { inventory, isOffline } = useSyncedData(); const { enqueue } = useOfflineInventory(); const [permission, requestPermission] = useCameraPermissions();
  const [container, setContainer] = useState<StorageContainer | null>(null); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<InventoryItem | null>(null); const [qty, setQty] = useState(1); const [cart, setCart] = useState<InventoryCartLine[]>([]); const [camera, setCamera] = useState(false); const [additionalFields, setAdditionalFields] = useState<AdditionalFormField[]>([]); const [submitting, setSubmitting] = useState(false); const scanLock = useRef<{ code: string; at: number } | null>(null);
  useFocusEffect(useCallback(() => { if (session && id) void fetchStorageContainer(session.token, id).then(setContainer).catch((e) => Alert.alert('Container unavailable', e.message)); }, [id, session]));
  const results = useMemo(() => { const q = query.trim().toLowerCase(); return inventory.filter((item) => !q || [item.name, item.sku, item.barcode, item.category].some((value) => String(value || '').toLowerCase().includes(q))).slice(0, 12); }, [inventory, query]);
  function choose(item: InventoryItem, scanned = false) { const now = Date.now(); const code = String(item.id); if (scanned && isDuplicateScan(scanLock.current, code, now)) return; if (cart.some((line) => line.itemId === item.id)) { Alert.alert('Already scanned', `${item.name} is already in the recent items list. Edit its quantity there.`); return; } scanLock.current = { code, at: now }; setSelected(item); setQuery(item.barcode || item.sku); setCamera(false); }
  function handleScan(code: string) { const normalized = code.trim().toLowerCase(); const item = inventory.find((row) => [row.barcode, row.sku, row.productCode, row.serialNumber].some((value) => String(value || '').toLowerCase() === normalized)); if (item) choose(item, true); else { setCamera(false); Alert.alert('Item not found', 'This code is not recorded as an active inventory item.'); } }
  function add() { if (!selected || qty <= 0) return; setCart((rows) => [{ clientLineId: Crypto.randomUUID(), itemId: selected.id, item: selected, qty, unit: selected.unit, condition: selected.conditionStatus || 'GOOD' }, ...rows]); setSelected(null); setQuery(''); setQty(1); }
  async function finish() { if (!session || !container || !cart.length || submitting) return; setSubmitting(true); const key = Crypto.randomUUID(); try { const input = { lines: cart.map((line) => ({ ...line, notes: mergeAdditionalFieldsIntoNotes(line.notes || '', additionalFields) || undefined })), idempotencyKey: key, deviceId: await getInstallationId() }; if (isOffline) { await enqueue({ endpoint: `/api/mobile/inventory/containers/${container.id}/items`, method: 'POST', label: `Add items to ${container.containerId}`, body: input, idempotencyKey: key }); Alert.alert('Saved Offline', 'Container changes are waiting to sync.', [{ text: 'Done', onPress: () => router.replace('/pending-sync' as never) }]); return; } try { await addContainerItems(session.token, container.id, input); Alert.alert('Container updated', `${cart.length} item types were added.`, [{ text: 'Done', onPress: () => router.replace({ pathname: '/container/[id]', params: { id: String(container.id) } } as never) }]); } catch (error) { if (error instanceof ApiError && error.status === 0) { await enqueue({ endpoint: `/api/mobile/inventory/containers/${container.id}/items`, method: 'POST', label: `Add items to ${container.containerId}`, body: input, idempotencyKey: key }); Alert.alert('Saved Offline', 'Container changes are waiting to sync.'); } else throw error; } } catch (e) { Alert.alert('Items not added', e instanceof Error ? e.message : 'Try again.'); } finally { setSubmitting(false); } }
  if (!container) return <LoadingScreen label="Selecting container" />;
  return <Screen><PageHeader title="Add to container" /><Surface style={styles.selectedContainer}><CheckCircle2 size={22} color={BRAND.green} /><View style={styles.main}><Text style={styles.banner}>Adding items to {container.containerId}</Text><Text style={styles.help}>{container.name} stays selected until you finish.</Text></View></Surface>
    <Text style={styles.heading}>1. Scan or search for an item</Text>{camera ? <View style={styles.camera}><CameraView style={StyleSheet.absoluteFill} barcodeScannerSettings={{ barcodeTypes: ['qr', 'ean13', 'ean8', 'code128', 'code39', 'upc_a', 'upc_e'] }} onBarcodeScanned={({ data }) => handleScan(data)} /><Pressable style={styles.close} onPress={() => setCamera(false)}><X color={BRAND.white} /></Pressable></View> : <View style={styles.searchRow}><TextInput value={query} onChangeText={(value) => { setQuery(value); setSelected(null); }} placeholder="Item name or barcode" placeholderTextColor={BRAND.muted} style={styles.search} /><Pressable onPress={async () => { if (!permission?.granted) { const result = await requestPermission(); if (!result.granted) return; } setCamera(true); }} style={styles.scan}><ScanLine size={23} color={BRAND.white} /></Pressable></View>}
    {!camera && query && !selected ? <Surface style={styles.results}>{results.map((item, index) => <Pressable key={item.id} onPress={() => choose(item)} style={[styles.result, index < results.length - 1 && styles.border]}><View style={styles.main}><Text style={styles.name}>{item.name}</Text><Text style={styles.help}>{item.barcode || item.sku} · {item.totalAvailable} available</Text></View><Plus size={20} color={BRAND.red} /></Pressable>)}</Surface> : null}
    {selected ? <Surface style={styles.editor}><Text style={styles.name}>{selected.name}</Text><Text style={styles.help}>Current available quantity: {selected.totalAvailable}</Text><Text style={styles.label}>2. Quantity being added</Text><View style={styles.qty}><Pressable style={styles.qtyButton} onPress={() => setQty(Math.max(1, qty - 1))}><Minus size={19} color={BRAND.ink} /></Pressable><TextInput value={String(qty)} onChangeText={(value) => setQty(Math.max(0, Number(value) || 0))} keyboardType="decimal-pad" style={styles.qtyInput} /><Pressable style={styles.qtyButton} onPress={() => setQty(qty + 1)}><Plus size={19} color={BRAND.ink} /></Pressable></View><RedButton onPress={add}>Add to Container</RedButton></Surface> : null}
    <View style={styles.recentTop}><Text style={styles.heading}>Recently scanned</Text><StatusChip label={`${cart.length} selected`} accent="violet" /></View>{cart.length ? cart.map((line) => <Surface key={line.clientLineId} style={styles.recent}><View style={styles.main}><Text style={styles.name}>{line.item?.name}</Text><Text style={styles.help}>{line.item?.barcode || line.item?.sku}</Text></View><TextInput value={String(line.qty)} onChangeText={(value) => setCart((rows) => rows.map((row) => row.clientLineId === line.clientLineId ? { ...row, qty: Math.max(0, Number(value) || 0) } : row))} keyboardType="decimal-pad" style={styles.smallQty} /><Pressable onPress={() => setCart((rows) => rows.filter((row) => row.clientLineId !== line.clientLineId))}><X size={20} color={BRAND.red} /></Pressable></Surface>) : <Text style={styles.empty}>Scan the first item. It will appear here for review.</Text>}
    <AdditionalFormFields fields={additionalFields} onChange={setAdditionalFields} /><OutlineButton icon={<ScanLine size={18} color={BRAND.inkSoft} />} onPress={() => setCamera(true)}>Scan another item</OutlineButton><View style={styles.finish}><RedButton disabled={!cart.length || submitting} onPress={finish}>{submitting ? 'Finishing…' : 'Finish Scanning'}</RedButton></View>
  </Screen>;
}

const styles = StyleSheet.create({ selectedContainer: { padding: 14, flexDirection: 'row', gap: 10, backgroundColor: BRAND.greenSoft }, main: { flex: 1, minWidth: 0 }, banner: { color: BRAND.green, fontFamily: TYPE.body, fontSize: 14, fontWeight: '800' }, help: { marginTop: 3, color: BRAND.muted, fontFamily: TYPE.body, fontSize: 11 }, heading: { marginTop: 20, marginBottom: 9, color: BRAND.ink, fontFamily: TYPE.body, fontSize: 17, fontWeight: '800' }, searchRow: { flexDirection: 'row', gap: 8 }, search: { flex: 1, minHeight: 50, borderRadius: 13, borderWidth: 1, borderColor: BRAND.line, paddingHorizontal: 13, color: BRAND.ink }, scan: { width: 52, borderRadius: 13, backgroundColor: BRAND.red, alignItems: 'center', justifyContent: 'center' }, camera: { height: 260, borderRadius: 17, overflow: 'hidden', backgroundColor: BRAND.ink }, close: { position: 'absolute', right: 12, top: 12, width: 38, height: 38, borderRadius: 19, backgroundColor: '#101A1FCC', alignItems: 'center', justifyContent: 'center' }, results: { marginTop: 8, overflow: 'hidden' }, result: { minHeight: 62, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13 }, border: { borderBottomWidth: 1, borderBottomColor: BRAND.line }, name: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 14, fontWeight: '700' }, editor: { marginTop: 10, padding: 14 }, label: { marginTop: 14, color: BRAND.inkSoft, fontFamily: TYPE.body, fontSize: 11, fontWeight: '700' }, qty: { marginVertical: 10, flexDirection: 'row', gap: 8 }, qtyButton: { width: 48, height: 48, borderRadius: 12, backgroundColor: BRAND.canvas, alignItems: 'center', justifyContent: 'center' }, qtyInput: { width: 78, height: 48, borderRadius: 12, borderWidth: 1, borderColor: BRAND.line, color: BRAND.ink, textAlign: 'center', fontWeight: '800' }, recentTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, recent: { minHeight: 64, marginBottom: 7, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 9 }, smallQty: { width: 55, height: 39, borderRadius: 9, borderWidth: 1, borderColor: BRAND.line, textAlign: 'center', color: BRAND.ink }, empty: { marginBottom: 16, color: BRAND.muted, fontFamily: TYPE.body, fontSize: 12 }, finish: { marginTop: 9 } });
