import { StyleSheet, Text, View } from 'react-native';
import { AlertTriangle, CheckCircle2, Clock3, RefreshCw } from 'lucide-react-native';
import { OutlineButton, PageHeader, RedButton, StatusChip, Surface } from '@/components/inventory-ui';
import { EmptyState, Screen } from '@/components/ui';
import { BRAND, TYPE } from '@/constants/brand';
import { useOfflineInventory } from '@/providers/offline-inventory-provider';
export default function PendingSyncScreen() { const { queue, pendingCount, conflictCount, syncing, sync, retry, dismissSynchronized } = useOfflineInventory(); return <Screen><PageHeader title="Pending Synchronization" /><Surface style={styles.summary}><Metric label="Waiting" value={pendingCount} color={BRAND.amber} /><Metric label="Conflicts" value={conflictCount} color={BRAND.red} /><Metric label="Synchronized" value={queue.filter((row) => row.status === 'SYNCHRONIZED').length} color={BRAND.green} /></Surface><Text style={styles.help}>Queued transactions keep their unique ID. The server rechecks quantities and will never post the same ID twice.</Text><RedButton disabled={syncing || !pendingCount} icon={<RefreshCw size={20} color={BRAND.white} />} onPress={() => void sync()}>{syncing ? 'Synchronizing…' : 'Synchronize Now'}</RedButton>{queue.map((row) => { const conflict = row.status === 'SYNC_CONFLICT'; const synced = row.status === 'SYNCHRONIZED'; return <Surface key={row.id} style={styles.row}><View style={styles.icon}>{conflict ? <AlertTriangle size={22} color={BRAND.red} /> : synced ? <CheckCircle2 size={22} color={BRAND.green} /> : <Clock3 size={22} color={BRAND.amber} />}</View><View style={styles.main}><Text style={styles.name}>{row.label}</Text><Text style={styles.meta}>{new Date(row.createdAt).toLocaleString()} · attempt {row.retryCount + 1}</Text>{row.lastError ? <Text style={styles.error}>{row.lastError}</Text> : null}<StatusChip label={row.status.replaceAll('_', ' ')} accent={conflict ? 'red' : synced ? 'green' : 'amber'} compact />{conflict ? <OutlineButton accent="red" onPress={() => void retry(row.id)} style={styles.retry}>Review and Retry</OutlineButton> : null}</View></Surface>; })}{!queue.length ? <EmptyState title="Everything is synchronized" message="Offline inventory transactions will appear here until the server accepts them." /> : null}{queue.some((row) => row.status === 'SYNCHRONIZED') ? <OutlineButton accent="green" onPress={() => void dismissSynchronized()}>Clear Synchronized</OutlineButton> : null}</Screen>; }
function Metric({ label, value, color }: { label: string; value: number; color: string }) { return <View style={styles.metric}><Text style={[styles.value, { color }]}>{value}</Text><Text style={styles.label}>{label}</Text></View>; }
const styles = StyleSheet.create({ summary: { padding: 14, flexDirection: 'row', marginBottom: 9 }, metric: { flex: 1, alignItems: 'center' }, value: { fontFamily: TYPE.body, fontSize: 22, fontWeight: '800' }, label: { color: BRAND.muted, fontFamily: TYPE.body, fontSize: 10 }, help: { marginBottom: 14, color: BRAND.muted, fontFamily: TYPE.body, fontSize: 11, lineHeight: 16 }, row: { marginTop: 9, padding: 13, flexDirection: 'row', alignItems: 'flex-start', gap: 9 }, icon: { width: 38, height: 38, borderRadius: 11, backgroundColor: BRAND.canvas, alignItems: 'center', justifyContent: 'center' }, main: { flex: 1 }, name: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 13, fontWeight: '700' }, meta: { marginVertical: 4, color: BRAND.muted, fontFamily: TYPE.body, fontSize: 10 }, error: { marginBottom: 6, color: BRAND.red, fontFamily: TYPE.body, fontSize: 10, lineHeight: 14 }, retry: { marginTop: 8 } });
