import { useCallback, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect } from 'expo-router';
import { ChevronRight, RotateCcw } from 'lucide-react-native';
import { PageHeader, StatusChip, Surface } from '@/components/inventory-ui';
import { EmptyState, LoadingScreen, Screen } from '@/components/ui';
import { BRAND, TYPE } from '@/constants/brand';
import { fetchPendingExcess } from '@/lib/api';
import { useAuth } from '@/providers/auth-provider';
import type { PendingExcessDeclaration } from '@/types/domain';
export default function PendingExcessScreen() { const { session } = useAuth(); const [rows, setRows] = useState<PendingExcessDeclaration[] | null>(null); const [error, setError] = useState(''); const load = useCallback(async () => { if (!session) return; try { setRows((await fetchPendingExcess(session.token)).data); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load returns'); } }, [session]); useFocusEffect(useCallback(() => { void load(); }, [load])); if (!rows && !error) return <LoadingScreen label="Loading pending returns" />; return <Screen><PageHeader title="Receive Excess" /><Text style={styles.title}>Pending Excess Returns</Text><Text style={styles.help}>Select a project declaration, physically scan and inspect every returned item.</Text>{error ? <EmptyState error title="Returns unavailable" message={error} /> : rows?.length ? rows.map((row) => <Surface key={row.id} onPress={() => router.push({ pathname: '/receive-excess/[id]', params: { id: String(row.id) } } as never)} style={styles.row}><View style={styles.icon}><RotateCcw size={22} color={BRAND.amber} /></View><View style={styles.main}><Text style={styles.name}>{row.project?.name || `Project ${row.projectId}`}</Text><Text style={styles.help}>{row.declarationNo} · {(row.lines || row.ExcessDeclarationLine || []).length} item types</Text></View><StatusChip label="Waiting" accent="amber" compact /><ChevronRight size={20} color={BRAND.muted} /></Surface>) : <EmptyState title="No pending excess" message="Submitted project excess will wait here until physically accepted." />}</Screen>; }
const styles = StyleSheet.create({ title: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 20, fontWeight: '800' }, help: { marginTop: 4, marginBottom: 12, color: BRAND.muted, fontFamily: TYPE.body, fontSize: 11, lineHeight: 16 }, row: { minHeight: 74, marginBottom: 8, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 9 }, icon: { width: 43, height: 43, borderRadius: 12, backgroundColor: BRAND.amberSoft, alignItems: 'center', justifyContent: 'center' }, main: { flex: 1 }, name: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 14, fontWeight: '700' } });
