import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, View } from 'react-native';
import * as Crypto from 'expo-crypto';
import { router, useLocalSearchParams } from 'expo-router';
import { PageHeader, RedButton, StatusChip, Surface } from '@/components/inventory-ui';
import { AdditionalFormFields, mergeAdditionalFieldsIntoNotes, type AdditionalFormField } from '@/components/additional-form-fields';
import { LoadingScreen, Screen } from '@/components/ui';
import { BRAND, TYPE } from '@/constants/brand';
import { fetchStorageContainer, submitContainerCount } from '@/lib/api';
import { getInstallationId } from '@/lib/storage';
import { useAuth } from '@/providers/auth-provider';
import type { StorageContainer } from '@/types/domain';

export default function CountContainerScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const { session } = useAuth(); const [data, setData] = useState<StorageContainer | null>(null); const [counts, setCounts] = useState<Record<number, string>>({}); const [additionalFields, setAdditionalFields] = useState<AdditionalFormField[]>([]); const [busy, setBusy] = useState(false); useEffect(() => { if (session && id) void fetchStorageContainer(session.token, id).then(setData).catch((e) => Alert.alert('Unable to open', e.message)); }, [id, session]); if (!data) return <LoadingScreen label="Loading count" />; const container = data; const complete = container.items.length > 0 && container.items.every((row) => counts[row.id] !== undefined && counts[row.id] !== ''); async function submit() { if (!session || !complete) return; setBusy(true); try { await submitContainerCount(session.token, container.id, { idempotencyKey: Crypto.randomUUID(), deviceId: await getInstallationId(), notes: mergeAdditionalFieldsIntoNotes('', additionalFields) || undefined, lines: container.items.map((row) => ({ itemId: row.inventoryItemId, batchId: row.batch?.id, expectedQty: row.qty, countedQty: Number(counts[row.id]), unit: row.item.unit || undefined, condition: row.condition })) }); Alert.alert('Count recorded', 'Any variance is in the audit history and does not silently change stock.', [{ text: 'Done', onPress: () => router.replace({ pathname: '/container/[id]', params: { id: String(container.id) } } as never) }]); } catch (e) { Alert.alert('Count not saved', e instanceof Error ? e.message : 'Try again.'); } finally { setBusy(false); } } return <Screen><PageHeader title="Count contents" /><Text style={styles.help}>Count every line in {container.containerId}. This records the result; it does not adjust quantities automatically.</Text>{container.items.map((row) => { const entered = counts[row.id]; const variance = entered === undefined || entered === '' ? null : Number(entered) - row.qty; return <Surface key={row.id} style={styles.row}><View style={styles.main}><Text style={styles.name}>{row.item.name}</Text><Text style={styles.help}>Expected {row.qty} {row.item.unit}</Text></View><View><TextInput value={entered || ''} onChangeText={(value) => setCounts((values) => ({ ...values, [row.id]: value }))} keyboardType="decimal-pad" placeholder="Count" style={styles.qty} />{variance !== null ? <StatusChip label={variance === 0 ? 'Matches' : `Variance ${variance > 0 ? '+' : ''}${variance}`} accent={variance === 0 ? 'green' : 'amber'} compact /> : null}</View></Surface>})}<AdditionalFormFields fields={additionalFields} onChange={setAdditionalFields} /><RedButton disabled={!complete || busy} onPress={submit}>{busy ? 'Saving…' : 'Record Count'}</RedButton></Screen>; }
const styles = StyleSheet.create({ help: { color: BRAND.muted, fontFamily: TYPE.body, fontSize: 12, lineHeight: 17 }, row: { minHeight: 83, marginVertical: 5, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10 }, main: { flex: 1 }, name: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 14, fontWeight: '700' }, qty: { width: 72, height: 43, marginBottom: 4, borderRadius: 10, borderWidth: 1, borderColor: BRAND.line, textAlign: 'center', color: BRAND.ink } });
