import { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Check, MapPin } from 'lucide-react-native';
import { PageHeader, RedButton, Surface } from '@/components/inventory-ui';
import { LoadingScreen, Screen } from '@/components/ui';
import { BRAND, TYPE } from '@/constants/brand';
import { fetchStockRoomMap, fetchStorageContainer, moveStorageContainer } from '@/lib/api';
import { useAuth } from '@/providers/auth-provider';
import type { StockRoomMap, StorageContainer } from '@/types/domain';

export default function MoveContainerScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const { session } = useAuth(); const [container, setContainer] = useState<StorageContainer | null>(null); const [map, setMap] = useState<StockRoomMap | null>(null); const [shelfId, setShelfId] = useState<number | null>(null); const [busy, setBusy] = useState(false); useEffect(() => { if (!session || !id) return; void fetchStorageContainer(session.token, id).then((row) => { setContainer(row); setShelfId(row.shelfId || null); void fetchStockRoomMap(session.token, row.stockRoomId).then(setMap); }).catch((e) => Alert.alert('Unable to open', e.message)); }, [id, session]); if (!container || !map) return <LoadingScreen label="Loading shelves" />; async function move() { if (!session || !shelfId || !container) return; setBusy(true); try { await moveStorageContainer(session.token, container.id, shelfId); Alert.alert('Container moved', 'The new rack and shelf are now recorded.', [{ text: 'Done', onPress: () => router.replace({ pathname: '/container/[id]', params: { id: String(container.id) } } as never) }]); } catch (e) { Alert.alert('Move not completed', e instanceof Error ? e.message : 'Try again.'); } finally { setBusy(false); } } return <Screen><PageHeader title="Move container" /><Surface style={styles.banner}><MapPin size={23} color={BRAND.violet} /><View style={styles.main}><Text style={styles.title}>{container.name}</Text><Text style={styles.help}>Choose one destination shelf in this stock room.</Text></View></Surface>{map.racks.map((rack) => <View key={rack.id}><Text style={styles.rack}>{rack.name}</Text>{rack.shelves.map((shelf) => <Pressable key={shelf.id} onPress={() => setShelfId(shelf.id)} style={[styles.option, shelfId === shelf.id && styles.active]}><View style={styles.main}><Text style={styles.name}>{shelf.name}</Text><Text style={styles.help}>{rack.code} → {shelf.code}</Text></View>{shelfId === shelf.id ? <Check size={21} color={BRAND.red} /> : null}</Pressable>)}</View>)}<RedButton disabled={!shelfId || busy} onPress={move}>{busy ? 'Moving…' : 'Confirm New Location'}</RedButton></Screen>; }
const styles = StyleSheet.create({ banner: { padding: 14, flexDirection: 'row', gap: 10, backgroundColor: BRAND.violetSoft }, main: { flex: 1 }, title: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 16, fontWeight: '800' }, help: { marginTop: 3, color: BRAND.muted, fontFamily: TYPE.body, fontSize: 11 }, rack: { marginTop: 19, marginBottom: 7, color: BRAND.ink, fontFamily: TYPE.body, fontSize: 17, fontWeight: '800' }, option: { minHeight: 61, marginBottom: 7, borderRadius: 13, borderWidth: 1, borderColor: BRAND.line, backgroundColor: BRAND.white, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center' }, active: { borderColor: BRAND.red, backgroundColor: BRAND.redSoft }, name: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 14, fontWeight: '700' } });
