import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import * as Crypto from 'expo-crypto';
import { router, useLocalSearchParams } from 'expo-router';
import { CheckSquare, ScanLine, Square, Trash2 } from 'lucide-react-native';
import { PageHeader, RedButton, StatusChip, Surface } from '@/components/inventory-ui';
import { AdditionalFormFields, mergeAdditionalFieldsIntoNotes, type AdditionalFormField } from '@/components/additional-form-fields';
import { PhotoEvidence, type LocalPhoto } from '@/components/photo-evidence';
import { LoadingScreen, Screen } from '@/components/ui';
import { BRAND, TYPE } from '@/constants/brand';
import { ApiError, fetchProjectInventory, submitProjectExcess, uploadProjectWorkflowPhoto } from '@/lib/api';
import { getInstallationId } from '@/lib/storage';
import { useAuth } from '@/providers/auth-provider';
import { useSyncedData } from '@/providers/data-provider';
import { useOfflineInventory } from '@/providers/offline-inventory-provider';
import type { ProjectInventoryItem, ProjectInventoryWorkspace } from '@/types/domain';

type Line = { key: string; row: ProjectInventoryItem; qty: number; condition: string; reason: string };
const conditions = ['GOOD', 'DEFECTIVE', 'DAMAGED', 'INCOMPLETE', 'FOR_REPAIR', 'UNDER_WARRANTY'];
export default function DeclareProjectExcessScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { session } = useAuth(); const { isOffline } = useSyncedData(); const { enqueue } = useOfflineInventory();
  const [data, setData] = useState<ProjectInventoryWorkspace | null>(null); const [query, setQuery] = useState(''); const [cart, setCart] = useState<Line[]>([]); const [photos, setPhotos] = useState<LocalPhoto[]>([]); const [notes, setNotes] = useState(''); const [additionalFields, setAdditionalFields] = useState<AdditionalFormField[]>([]); const [busy, setBusy] = useState(false); const [key] = useState(() => Crypto.randomUUID());
  useEffect(() => { if (session && id) void fetchProjectInventory(session.token, Number(id)).then(setData).catch((e) => Alert.alert('Project unavailable', e.message)); }, [id, session]);
  const available = useMemo(() => { const q = query.trim().toLowerCase(); return (data?.items || []).filter((row) => row.remainingQty > 0 && (!q || [row.item.name, row.item.sku, row.item.barcode].some((value) => String(value || '').toLowerCase().includes(q)))); }, [data, query]);
  if (!data) return <LoadingScreen label="Loading project items" />; const workspace = data;
  function add(row: ProjectInventoryItem) { if (!cart.some((line) => line.row.inventoryItemId === row.inventoryItemId)) setCart((lines) => [...lines, { key: Crypto.randomUUID(), row, qty: 1, condition: 'GOOD', reason: '' }]); }
  function patch(keyValue: string, values: Partial<Line>) { setCart((lines) => lines.map((line) => line.key === keyValue ? { ...line, ...values } : line)); }
  function scan() { const value = query.trim().toLowerCase(); const found = workspace.items.find((row) => [row.item.barcode, row.item.sku].some((code) => String(code || '').toLowerCase() === value)); if (!found) Alert.alert('Not found', 'This item is not recorded under this project.'); else if (found.remainingQty <= 0) Alert.alert('No remaining quantity', 'Only unused or remaining project quantity can be declared.'); else add(found); }
  async function submit() {
    if (!session || !cart.length || busy) return; if (cart.some((line) => !line.reason.trim() || line.qty <= 0 || line.qty > line.row.remainingQty)) return Alert.alert('Review excess items', 'Every line needs a valid quantity, condition and reason.'); setBusy(true);
    try { const evidenceIds = isOffline ? [] : (await Promise.all(photos.map((photo) => uploadProjectWorkflowPhoto(session.token, workspace.project.id, { ...photo, kind: 'EXCESS_DECLARATION' })))).map((row) => row.id); const input = { idempotencyKey: key, deviceId: await getInstallationId(), notes: mergeAdditionalFieldsIntoNotes(notes, additionalFields) || undefined, lines: cart.map((line) => ({ itemId: line.row.inventoryItemId, qty: line.qty, condition: line.condition, reason: line.reason, containerId: line.row.containerId || undefined, evidenceIds })) };
      if (isOffline) { await enqueue({ endpoint: `/api/mobile/inventory/projects/${workspace.project.id}/excess`, method: 'POST', label: `Declare excess · ${workspace.project.name}`, body: input, idempotencyKey: key }); Alert.alert('Saved Offline', 'This declaration is waiting to sync.', [{ text: 'Done', onPress: () => router.replace('/pending-sync' as never) }]); return; }
      try { const result = await submitProjectExcess(session.token, workspace.project.id, input); Alert.alert('Excess declared', result.message, [{ text: 'Done', onPress: () => router.replace({ pathname: '/projects/[id]', params: { id: String(workspace.project.id) } } as never) }]); } catch (error) { if (error instanceof ApiError && error.status === 0) { await enqueue({ endpoint: `/api/mobile/inventory/projects/${workspace.project.id}/excess`, method: 'POST', label: `Declare excess · ${workspace.project.name}`, body: input, idempotencyKey: key }); Alert.alert('Saved Offline', 'This declaration is waiting to sync.'); } else throw error; }
    } catch (error) { Alert.alert('Declaration not submitted', error instanceof Error ? error.message : 'Try again.'); } finally { setBusy(false); }
  }
  return <Screen><PageHeader title="Declare Excess" /><Surface style={styles.banner}><Text style={styles.bannerTitle}>{workspace.project.name}</Text><Text style={styles.help}>Declaring excess does not increase stock-room quantity until the physical return is accepted.</Text></Surface><Text style={styles.heading}>1. Scan or choose items</Text><View style={styles.searchRow}><TextInput value={query} onChangeText={setQuery} placeholder="Project item name or barcode" placeholderTextColor={BRAND.muted} style={styles.search} /><Pressable onPress={scan} style={styles.scan}><ScanLine size={22} color={BRAND.white} /></Pressable></View><View style={styles.selected}><StatusChip label={`${cart.length} items selected`} accent="violet" /><Pressable onPress={() => available.forEach(add)}><Text style={styles.selectAll}>Select all valid</Text></Pressable></View>{available.map((row) => { const active = cart.some((line) => line.row.inventoryItemId === row.inventoryItemId); return <Surface key={row.id} onPress={() => add(row)} style={styles.item}>{active ? <CheckSquare size={22} color={BRAND.red} /> : <Square size={22} color={BRAND.muted} />}<View style={styles.main}><Text style={styles.name}>{row.item.name}</Text><Text style={styles.help}>Released {row.releasedQty} · Used {row.usedQty} · Remaining {row.remainingQty}</Text></View></Surface>; })}<Text style={styles.heading}>2. Enter excess details</Text>{cart.map((line) => <Surface key={line.key} style={styles.editor}><View style={styles.top}><View style={styles.main}><Text style={styles.name}>{line.row.item.name}</Text><Text style={styles.help}>Maximum {line.row.remainingQty} {line.row.item.unit}</Text></View><Pressable onPress={() => setCart((rows) => rows.filter((row) => row.key !== line.key))}><Trash2 size={20} color={BRAND.red} /></Pressable></View><TextInput value={String(line.qty)} onChangeText={(value) => patch(line.key, { qty: Math.min(line.row.remainingQty, Math.max(0, Number(value) || 0)) })} keyboardType="decimal-pad" style={styles.qty} /><View style={styles.chips}>{conditions.map((condition) => <Text key={condition} onPress={() => patch(line.key, { condition })} style={[styles.chip, line.condition === condition && styles.chipActive]}>{condition.replaceAll('_', ' ')}</Text>)}</View><TextInput value={line.reason} onChangeText={(value) => patch(line.key, { reason: value })} placeholder="Reason (required)" placeholderTextColor={BRAND.muted} style={styles.reason} /></Surface>)}<PhotoEvidence label="Item photos" photos={photos} onChange={setPhotos} multiple /><TextInput value={notes} onChangeText={setNotes} multiline placeholder="Declaration notes (optional)" placeholderTextColor={BRAND.muted} style={styles.notes} /><AdditionalFormFields fields={additionalFields} onChange={setAdditionalFields} /><RedButton disabled={!cart.length || busy} onPress={submit}>{busy ? 'Submitting…' : 'Submit Excess Declaration'}</RedButton></Screen>;
}
const styles = StyleSheet.create({ banner: { padding: 14, backgroundColor: BRAND.violetSoft }, bannerTitle: { color: BRAND.violet, fontFamily: TYPE.body, fontSize: 15, fontWeight: '800' }, help: { marginTop: 3, color: BRAND.muted, fontFamily: TYPE.body, fontSize: 11, lineHeight: 16 }, heading: { marginTop: 20, marginBottom: 9, color: BRAND.ink, fontFamily: TYPE.body, fontSize: 17, fontWeight: '800' }, searchRow: { flexDirection: 'row', gap: 8 }, search: { flex: 1, height: 49, borderRadius: 12, borderWidth: 1, borderColor: BRAND.line, paddingHorizontal: 12, color: BRAND.ink }, scan: { width: 50, borderRadius: 12, backgroundColor: BRAND.red, alignItems: 'center', justifyContent: 'center' }, selected: { marginVertical: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, selectAll: { color: BRAND.red, fontFamily: TYPE.body, fontSize: 11, fontWeight: '800' }, item: { minHeight: 65, marginBottom: 7, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10 }, main: { flex: 1 }, name: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 14, fontWeight: '700' }, editor: { marginBottom: 9, padding: 13 }, top: { flexDirection: 'row', alignItems: 'center' }, qty: { width: 75, height: 43, marginTop: 10, borderRadius: 10, borderWidth: 1, borderColor: BRAND.line, textAlign: 'center', color: BRAND.ink }, chips: { marginTop: 9, flexDirection: 'row', flexWrap: 'wrap', gap: 5 }, chip: { borderRadius: 8, backgroundColor: BRAND.canvas, color: BRAND.inkSoft, paddingHorizontal: 8, paddingVertical: 7, fontFamily: TYPE.body, fontSize: 9, fontWeight: '700' }, chipActive: { backgroundColor: BRAND.redSoft, color: BRAND.red }, reason: { height: 45, marginTop: 9, borderRadius: 10, borderWidth: 1, borderColor: BRAND.line, paddingHorizontal: 11, color: BRAND.ink }, notes: { minHeight: 78, marginVertical: 10, borderRadius: 11, borderWidth: 1, borderColor: BRAND.line, padding: 11, textAlignVertical: 'top' } });
