import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { CheckCircle2, Truck } from 'lucide-react-native';
import { PageHeader, RedButton, StatusChip, Surface } from '@/components/inventory-ui';
import { AdditionalFormFields, mergeAdditionalFieldsIntoNotes, type AdditionalFormField } from '@/components/additional-form-fields';
import { PhotoEvidence, type LocalPhoto } from '@/components/photo-evidence';
import { SignaturePad } from '@/components/signature-pad';
import { LoadingScreen, Screen } from '@/components/ui';
import { BRAND, TYPE } from '@/constants/brand';
import { confirmProjectInventoryReceipt, fetchProjectInventory, uploadProjectWorkflowPhoto } from '@/lib/api';
import { useAuth } from '@/providers/auth-provider';
import type { ProjectInventoryWorkspace } from '@/types/domain';

export default function ProjectReceiptScreen() {
  const params = useLocalSearchParams<{ id: string; receiptId: string }>(); const { session } = useAuth();
  const [data, setData] = useState<ProjectInventoryWorkspace | null>(null); const [qtys, setQtys] = useState<Record<number, string>>({}); const [conditions, setConditions] = useState<Record<number, string>>({}); const [signature, setSignature] = useState<[number, number][][]>([]); const [note, setNote] = useState(''); const [photos, setPhotos] = useState<LocalPhoto[]>([]); const [additionalFields, setAdditionalFields] = useState<AdditionalFormField[]>([]); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!session) return; void fetchProjectInventory(session.token, Number(params.id)).then((workspace) => { setData(workspace); const current = workspace.receipts.find((row) => row.id === Number(params.receiptId)); const initial: Record<number, string> = {}; current?.InventoryTransaction?.InventoryTransactionLine.forEach((line) => { initial[line.inventoryItemId] = String(line.qty); }); setQtys(initial); }).catch((error) => Alert.alert('Release unavailable', error.message)); }, [params.id, params.receiptId, session]);
  if (!data) return <LoadingScreen label="Opening incoming release" />; const workspace = data; const receipt = workspace.receipts.find((row) => row.id === Number(params.receiptId)); if (!receipt?.InventoryTransaction) return <Screen><PageHeader title="Project Receipt" /><Text>Release details are unavailable.</Text></Screen>; const transaction = receipt.InventoryTransaction; const lines = transaction.InventoryTransactionLine;
  async function submit() { if (!session || !signature.length) return Alert.alert('Signature required', 'The project receiver must sign before confirmation.'); setBusy(true); try { const evidenceIds = (await Promise.all(photos.map((photo) => uploadProjectWorkflowPhoto(session.token, workspace.project.id, { ...photo, kind: 'PROJECT_RECEIPT' })))).map((row) => row.id); const result = await confirmProjectInventoryReceipt(session.token, workspace.project.id, receipt!.id, { lines: lines.map((line) => ({ itemId: line.inventoryItemId, qty: Math.max(0, Math.min(line.qty, Number(qtys[line.inventoryItemId]) || 0)), condition: conditions[line.inventoryItemId] || 'GOOD' })), signatureStrokes: signature, discrepancyNote: mergeAdditionalFieldsIntoNotes(note, additionalFields) || undefined, evidenceIds }); Alert.alert('Receipt confirmed', result.status.replaceAll('_', ' '), [{ text: 'Done', onPress: () => router.replace({ pathname: '/projects/[id]', params: { id: String(workspace.project.id) } } as never) }]); } catch (error) { Alert.alert('Receipt not confirmed', error instanceof Error ? error.message : 'Try again.'); } finally { setBusy(false); } }
  return <Screen><PageHeader title="Confirm Project Receipt" /><Surface style={styles.banner}><Truck size={24} color={BRAND.violet} /><View style={styles.main}><Text style={styles.title}>{transaction.transactionNo}</Text><Text style={styles.help}>Released From Stock Room → verify what physically arrived.</Text></View><StatusChip label={receipt.status.replaceAll('_', ' ')} accent="violet" compact /></Surface><Text style={styles.heading}>1. Compare every item</Text>{lines.map((line) => { const itemId = line.inventoryItemId; const item = workspace.items.find((row) => row.inventoryItemId === itemId)?.item; const condition = conditions[itemId] || 'GOOD'; return <Surface key={line.id} style={styles.card}><Text style={styles.name}>{item?.name || `Item ${itemId}`}</Text><Text style={styles.help}>Released: {line.qty} {line.unit}</Text><Text style={styles.label}>Quantity received</Text><TextInput value={qtys[itemId] || ''} onChangeText={(value) => setQtys((rows) => ({ ...rows, [itemId]: value }))} keyboardType="decimal-pad" style={styles.input} /><View style={styles.chips}>{['GOOD', 'DAMAGED', 'MISSING', 'INCOMPLETE'].map((value) => <Text key={value} onPress={() => setConditions((rows) => ({ ...rows, [itemId]: value }))} style={[styles.chip, condition === value && styles.chipActive]}>{value}</Text>)}</View></Surface>; })}<Text style={styles.heading}>2. Add evidence if needed</Text><PhotoEvidence label="Missing or damaged item photos" photos={photos} onChange={setPhotos} multiple /><TextInput value={note} onChangeText={setNote} multiline placeholder="Explain missing, damaged or partial quantities" placeholderTextColor={BRAND.muted} style={styles.notes} /><AdditionalFormFields fields={additionalFields} onChange={setAdditionalFields} /><Text style={styles.heading}>3. Receiver signature</Text><SignaturePad value={signature} onChange={setSignature} /><View style={styles.finish}><RedButton disabled={busy} icon={<CheckCircle2 size={20} color={BRAND.white} />} onPress={submit}>{busy ? 'Confirming…' : 'Confirm Project Receipt'}</RedButton></View></Screen>;
}
const styles = StyleSheet.create({ banner: { padding: 14, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: BRAND.violetSoft }, main: { flex: 1 }, title: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 15, fontWeight: '800' }, help: { marginTop: 3, color: BRAND.muted, fontFamily: TYPE.body, fontSize: 11, lineHeight: 16 }, heading: { marginTop: 20, marginBottom: 9, color: BRAND.ink, fontFamily: TYPE.body, fontSize: 17, fontWeight: '800' }, card: { marginBottom: 8, padding: 13 }, name: { color: BRAND.ink, fontFamily: TYPE.body, fontSize: 14, fontWeight: '700' }, label: { marginTop: 10, marginBottom: 5, color: BRAND.inkSoft, fontFamily: TYPE.body, fontSize: 10, fontWeight: '700' }, input: { width: 90, height: 44, borderRadius: 10, borderWidth: 1, borderColor: BRAND.line, color: BRAND.ink, textAlign: 'center' }, chips: { marginTop: 9, flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, chip: { borderRadius: 8, backgroundColor: BRAND.canvas, paddingHorizontal: 9, paddingVertical: 7, color: BRAND.inkSoft, fontFamily: TYPE.body, fontSize: 9, fontWeight: '700' }, chipActive: { backgroundColor: BRAND.redSoft, color: BRAND.red }, notes: { minHeight: 83, marginTop: 9, borderRadius: 12, borderWidth: 1, borderColor: BRAND.line, padding: 11, textAlignVertical: 'top' }, finish: { marginTop: 14 } });
